### PR TITLE
Update Kotlin version to M14

### PR DESCRIPTION
**Pull request by koesie10**
Fixes https://github.com/JakeWharton/RxBinding/issues/157

### CODE REVIEW

**Comment by JakeWharton** [comment]
Well that was easy! Thanks

**Comment by koesie10** [comment]
Why does Travis fail on dexDebugAndroidTest?

**Comment by JakeWharton** [comment]
Low memory

**Comment by JakeWharton** [comment]
I restarted it

**Comment by koesie10** [comment]
It still doesn't build, but it builds locally.

**Comment by koesie10** [comment]
When will you release a new version so that this and all other new features can be used without a snapshot version?

**Pull request merged**
