### PR TITLE
Add kotlin dependency

### PR DESCRIPTION
**Pull request by cloudshooterhuman**

### CODE REVIEW

**Comment by JakeWharton** [comment]
The whole library has been written in Kotlin since 3.x. There is no Kotlin-specific dependency anymore.

**Comment by cloudshooterhuman** [comment]
Playing with a little Android project I only get `RxView`  when I added 

    implementation 'com.jakewharton.rxbinding:rxbinding-kotlin:0.4.0'

**build.gradle**

```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 29

    defaultConfig {
        applicationId "com.unune.andoridapp"
        minSdkVersion 16
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.3.1'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    implementation 'com.jakewharton.timber:timber:4.7.1'

    implementation group: 'io.reactivex.rxjava2', name: 'rxjava', version: '2.2.19'
    implementation group: 'io.reactivex.rxjava2', name: 'rxandroid', version: '2.1.1'


    implementation 'com.jakewharton.rxbinding:rxbinding-kotlin:0.4.0'
}
```

**Comment by JakeWharton** [comment]
`RxView` is only available to Java callers. In Kotlin everything is defined as extensions on `View` (or whatever class you're targeting).

**Comment by cloudshooterhuman** [comment]
Hmm thanks JW.

**Pull request closed without merging**
