### PR TITLE
Publish sources to Maven Central

### LINKED ISSUE #526: Source not available in the IDE
For tracking, and because I don't know how to debug that.

The IDE would just show stubs from the class files. Clicking _download source_ doesn't do much. The logs says it fails
> 13:27	Executing tasks: [DownloadSources] in project /Users/bquenaudon/workspace/cash-android
> 13:27	Gradle build failed in 5 s 866 ms

### PR DESCRIPTION
**Pull request by oldergod**
fixed #526

### CODE REVIEW

**Comment by oldergod** [comment]
Not fixed.

**Comment by oldergod** [comment]
Let's do it. Copy/paster John from https://github.com/square/leakcanary/pull/1644

**Comment by JakeWharton** [comment]
Have you checked the output to confirm they're there? If not, I can.

**Comment by oldergod** [comment]
I did not. So please do.

**Comment by JakeWharton** [comment]
It works.

**Comment by artem-zinnatullin** [comment]
@JakeWharton if it's not too hard do you mind shipping a patch release to get sources up? Thanks

**Comment by PaulKlauser** [comment]
☝️ Would be much appreciated

**Pull request merged**
