### PR TITLE
Add ActionBar MenuVisibilityChange event binding

### PR DESCRIPTION
**Pull request by xfumihiro**

### CODE REVIEW

**Comment by JakeWharton** [comment]
Is this callback useful for anything? I never understood why it existed and can't think of a use for it.

**Comment by JakeWharton** [comment]
The first 20 pages of https://github.com/search?l=java&p=1&q=OnMenuVisibilityListener&type=Code&utf8=%E2%9C%93 show not a single real usage in user code.

**Comment by xfumihiro** [comment]
Wow, didn't know about that. Just surfing through API and thought adding it might help. If that's the case just drop this PR.

**Comment by JakeWharton** [comment]
Yeah I think we just hold off on this one unless someone explicitly requests it. There's infrequently used listeners and then there's this one which seems to be in a whole class of its own.

**Pull request closed without merging**
