### PR TITLE
Added SnackbarActionOnSubscribe to v2

### PR DESCRIPTION
**Pull request by aballano**
Converted #302 to v2.

### CODE REVIEW

**Comment by Shyish** [comment]
Seems that  rxbinding-appcompat-v7 has a flaky test (?)

> com.jakewharton.rxbinding2.support.v7.widget.RxToolbarTest > navigationClicks[test(AVD) - 4.3.1] FAILED 
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not be requesting layout for over 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Otherwise, something is seriously wrong. Selected Root:
	Root{application-window-token=android.view.ViewRootImpl$W@b2eceb10, window-token=android.view.ViewRootImpl$W@b2eceb10, has-window-focus=false, layout-params-type=1, layout-params-string=WM.LayoutParams{(0,0)(fillxfill) sim=#100 ty=1 fl=#1810100 pfl=0x8 wanim=0x1030299}, decor-view-string=DecorView{id=-1, visibility=VISIBLE, width=480, height=800, has-focus=true, has-focusable=true, has-window-focus=false, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}}

Will try again

**Comment by JakeWharton** [comment]
There are many flaky tests, unfortunately.

**Comment by Rainer-Lang** [comment]
@aballano Could you fix it to get this PR merged?

**Comment by aballano** [comment]
Sorry for the delay! 

@JakeWharton Build is green now :)

**Pull request closed without merging**
