### PR TITLE
Added SnackbarActionOnSubscribe.

### PR DESCRIPTION
**Pull request by aballano**
Added 2 more methods in the RxSnackbar class to also observe interactions with the snackbar action.

Don't know exactly if is possible to emulate a click on the action from within the tests, any ideas?

### CODE REVIEW

**Comment by JakeWharton** [comment]
You should be able to click on it using withText using Espresso.

**Comment by Shyish** [comment]
@JakeWharton Done, please take another look

**Comment by JakeWharton** [comment]
I didn't take a first look! I will tomorrow though. Looking to get a new
release out soon.

**Comment by Shyish** [comment]
Oh then I'll try to be quick and create another PR with other additions I have :D

**Comment by JakeWharton** [comment]
Please!

**Comment by Shyish** [comment]
@JakeWharton Is there something I could do to fix the build? Or is it broken for the whole lib?

**Comment by shivan42** [comment]
Hi guys!
@Shyish Do you plan to complete this useful commit? It would be cool!
if I understand correctly the build was failed because you just forgot to run :generateKotlin task to generate Kotlin code and add it to commit.
@JakeWharton Do you plan to release new version of RxBinding 1.x.x, if this commit will be merged?

**Comment by Shyish** [comment]
Sorry I totally forgot about this PR. I executed the command but I guess it doesn't make much sense ATM since v1.x.x doesn't seem to be supported.

I could create a PR to update v2.x though.

**Pull request closed without merging**
