### PR TITLE
Notify observers if anything changes

### PR DESCRIPTION
**Pull request by diareuse**
Due to fact that onChanged() method responds only to notifyDataSetChanged() call, other calls (notifyItemChanged, notifyItemMoved, etc..) are left hanging. Observer has to be notified if any (and all) of those calls are invoked.

And I'm sorry for the import misplacement.

### CODE REVIEW

**Comment by diareuse** [comment]
https://github.com/JakeWharton/RxBinding/issues/310

**Comment by serj-lotutovici** [comment]
Maybe it makes sense to have an event object, that would reflect the type of change that occurred?
Otherwise the api seams incomplete.

**Comment by diareuse** [comment]
Idk whether that's necessary. Until now it wasn't supposed to reflect anything; just alert the subscriber that dataset changed which is by this commit extended for all dataset changes.

However I'm not saying that's bad idea.

**Comment by JakeWharton** [comment]
I'd rather have granular notifications for these available via a different overload.

**Comment by diareuse** [comment]
Do you mean something like supplying observer with some enum of state that has changed? Or absolutely different approach?

**Comment by JakeWharton** [comment]
We use auto value classes since each callback has to carry data. See item
selected / nothing selected for a spinner for an example.

**Pull request closed without merging**
