### PR TITLE
Add consumer ProGuard rules for AutoValue usage.

### LINKED ISSUE #427: Add consumer ProGuard rules to ignore missing AutoValue
Stupid auto value and their stupid class retention...

### PR DESCRIPTION
**Pull request by JakeWharton**
Closes #427

### CODE REVIEW

**Comment by vanniktech** [comment]
Is there any reason for putting it into src/main

**Comment by JakeWharton** [comment]
It's not a variant-specific config

**Comment by ming13** [comment]
Thanks, Jake! Any chance to make a minor release with this change?

**Comment by JakeWharton** [comment]
Maybe. I'd prefer to try and fix one or two other things first.

**Pull request merged**
