### PR TITLE
Add @CheckResult to all factory methods.

### PR DESCRIPTION
**Pull request by JakeWharton**
It is a programmer error to call these and ignore their return type.

(With apologies to @hzsweers... hope this doesn't break anything!)

### CODE REVIEW

**Comment by hzsweers** [comment]
Shouldn't break anything since I haven't touched the java files themselves, but does bring up another question. Do you want these annotations on the methods as well? Currently ignores them

**Comment by JakeWharton** [comment]
I'm fine with them being ignored. Lint can't handle Kotlin files anyway and if it ever does, we can just update the thing to copy them.

**Comment by hzsweers** [comment]
:+1:

**Comment by JakeWharton** [comment]
screen shot 2015-08-06 at 11 18 35 pm

**Comment by JakeWharton** [comment]
Stupid flaky test...

**Comment by hzsweers** [comment]
For the flakiness

**Pull request merged**
