### PR TITLE
Add checkstyle to projects and fix some errors

### PR DESCRIPTION
**Pull request by vanniktech**
Since you said you wanted Checkstyle in #195, I thought I'd add it.

The CI should fail as there are still some checkstyle errors. I did resolve some  errors. Though `Line longer than 100 characters`, `Comment matches // TOOD:` and `More than 7 parameters`, I did not since I don't know how you'd like to handle those errors.

The checkstyle.xml is from your [ButterKnife Project](https://github.com/JakeWharton/butterknife/blob/master/checkstyle.xml).

### CODE REVIEW

**Comment by JakeWharton** [comment]
What has more than 7 params?

**Comment by vanniktech** [comment]
[ViewLayoutChangeEvent.java:16](https://github.com/JakeWharton/RxBinding/blob/master/rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewLayoutChangeEvent.java#L16)
[ViewLayoutChangeEvent.java:24](https://github.com/JakeWharton/RxBinding/blob/master/rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewLayoutChangeEvent.java#L24)
[ViewLayoutChangeEventOnSubscribe.java:22](https://github.com/JakeWharton/RxBinding/blob/master/rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewLayoutChangeEventOnSubscribe.java#L22)
[ViewLayoutChangeOnSubscribe.java:21](https://github.com/JakeWharton/RxBinding/blob/master/rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewLayoutChangeOnSubscribe.java#L21)

**Comment by JakeWharton** [comment]
Ah, forgot those even existed. I'll have a look tomorrow!

**Comment by vanniktech** [comment]
What's also possible is to suppress some warnings using `@SuppressWarnings("checkstyle:<rule>")`. Though as far as I see the `checkstyle.xml` file would need to be configured for that.

**Pull request closed without merging**
