### PR TITLE
representing broadcast receiver and service connection with observable

### PR DESCRIPTION
**Pull request by emakar**
Just pretty curious would any non-ui components be added to this repository. As for now I'd like to get some feedback on these ones. Thanks!
(also it seemed like an issue to me that kotlin generator merges multiple method params, so I proposed a fix as well)

### CODE REVIEW

**Comment by JakeWharton** [comment]
This project is restricted to providing bindings for classes in the `*.view.*` and `*.widget.*` packages of `android` and the various UI support libraries. Without such restriction there's far too many APIs for writing Rx adapters.

For broadcasts there's at least two or three libraries out there attempting this. For example, here's one: https://github.com/cantrowitz/RxBroadcast

**Comment by emakar** [comment]
Ok, thanks. However don't you know some common repository for such things like ServiceConnection, BroadcastReceiver, preferences, etc? These are common things, it would be excellent having them altogether like ui stuff here

**Comment by JakeWharton** [comment]
There's a preferences one at https://github.com/f2prateek/rx-preferences/. I don't know of any common list.

**Comment by vanniktech** [comment]
This looks like a pretty neat list: https://github.com/zsoltk/RxAndroidLibs

**Comment by eleventigers** [comment]
@vanniktech for a more broad "awesome" RxJava list, shameless plug: https://github.com/eleventigers/awesome-rxjava

**Comment by emakar** [comment]
Great, thanks!

**Pull request closed without merging**
