### PR TITLE
Port to RxJava 2.

### LINKED ISSUE #281: RxJava 2.x variant
Just a placeholder issue for now.

### PR DESCRIPTION
**Pull request by JakeWharton**
Closes #281.

### CODE REVIEW

**Comment by marcin-kozinski** [comment]
Hey Jake, thanks for starting the work on this. I have a question about the changes you've made so far. It's more so I can learn and understand your choice, not so much trying to point out something I think is wrong.

Why did you take the route of subclassing `Observable` (for example `final class ViewTouchObservable extends Observable<MotionEvent>`) instead of using `Observable.create()`?

**Comment by JakeWharton** [comment]
This creates less objects.

**Comment by JakeWharton** [comment]
We're down to intermittent test failures so moving to `master`. Thanks everyone for the help.

**Comment by vanniktech** [comment]
What's the reason behind removing truth?

**Comment by JakeWharton** [comment]
Blew dex limit on test APK.

**Pull request merged**
