### PR TITLE
Add RxAutoCompleteTextView.itemClickEvents

### PR DESCRIPTION
**Pull request by JakeWharton**

### CODE REVIEW

**Comment by JakeWharton** [comment]
Ugh, wtf. This works fine locally.

**Comment by liericiyan** [comment]
What's that mean ‘wtf’?

**Comment by vanniktech** [comment]
What's the status on this one?

**Comment by JakeWharton** [comment]
It works, and the test work fine locally. For some reason the tests fail on Travis CI.

**Pull request merged**
