### PR TITLE
Add ViewPager page scroll state change binding

### PR DESCRIPTION
**Pull request by kunny**

### CODE REVIEW

**Comment by kunny** [comment]
```
The command "./gradlew ":$MODULE:build" ":$MODULE-kotlin:build" ":$MODULE:connectedCheck"" exited with 137.
```

It seems travis killed an emulator, but don't know why it happened at `leanback`.

**Comment by artem-zinnatullin** [comment]
Code 137 is usually OutOfMemory.

On Tue, Jul 12, 2016 at 6:50 PM Taeho Kim

<
mailto:Taeho Kim <notifications@github.com>
> wrote:

The command "./gradlew ":$MODULE:build" ":$MODULE-kotlin:build" ":$MODULE:connectedCheck"" exited with 137.

It seems travis killed an emulator, but don't know why it happened at

leanback

.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/JakeWharton/RxBinding/pull/268#issuecomment-232091734
, or
https://github.com/notifications/unsubscribe/AA7B3IZ8o1gN49g_WTNjd_fDdPmPC1R8ks5qU7fNgaJpZM4JKf63
.

https://github.com/JakeWharton/RxBinding/pull/268#issuecomment-232091734

**Comment by kunny** [comment]
@artem-zinnatullin Sounds like exact same issue as https://github.com/travis-ci/travis-ci/issues/5582
A build would pass if we do not run a travis build on the container-based one.

However, as this could be just temporary issue, I'll rebuild first before modifying travis.yml.

**Comment by JakeWharton** [comment]
Merged to `master` manually. Thanks!

**Pull request closed without merging**
