### PR TITLE
Port com.jakewharton.rxbinding.widget.RxTextView to RxJava 2

### PR DESCRIPTION
**Pull request by ghostbuster91**
This PR is based on #322 because it uses `Predicate`

### CODE REVIEW

**Comment by JakeWharton** [comment]
Can you rebase this so that I don't get double predicate commits?

**Comment by ghostbuster91** [comment]
Ofc, no problem.

**Comment by ghostbuster91** [comment]
Done.

**Comment by JakeWharton** [comment]
Thanks!

**Pull request merged**
