### PR TITLE
Add missing 'check result' annotations.

### PR DESCRIPTION
**Pull request by JakeWharton**

### CODE REVIEW

**Comment by JakeWharton** [comment]
@hzsweers I'm thinking we should expand the `buildSrc` plugin to verify certain commonalities to these factory methods. Verify `@CheckResult`, maybe `@NonNull` on the method and parameter (#20), verify things inside the documentation, etc.

**Comment by hzsweers** [comment]
That's reasonable, I can look at adding that this weekend.

To be clear, you're saying every method should (where appropriate) look
like this?

```java
@CheckResult @NonNull
public static SomeType myFunction(@NonNull SomeView view) {

}
```

**Comment by hzsweers** [comment]
I dream of a day that GitHub accepts markdown in email responses ಠ╭╮ಠ

**Comment by JakeWharton** [comment]
I found out it accepts emojis over emails the other day... I'll file a tracking issue for the change.

**Pull request merged**
