### PR TITLE
Change minSdkVersion from 15 to 14.

### PR DESCRIPTION
**Pull request by entertainyou**

### CODE REVIEW

**Comment by vekexasia** [comment]
Thanks, i'm looking forward to this modification too.

**Comment by JakeWharton** [comment]
How many users do you have on API 14?

**Comment by entertainyou** [comment]
@JakeWharton about five percent according to Umeng statistic(http://www.umindex.com/devices/android_os a popular third party statistic library in China)

**Comment by JakeWharton** [comment]
Ok. Fair enough.

**Comment by JakeWharton** [comment]
@entertainyou API 14 doesn't even show up on that chart.

**Comment by entertainyou** [comment]
@JakeWharton my bad, 4.0.3 and 4.0.4 is API 15, I though 4.x is API 14, :(.

**Pull request merged**
