### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by hzsweers**
Had to switch to jcenter for the android gradle plugin. Deferring the kotlin update to #255

### CODE REVIEW

**Comment by hzsweers** [comment]
Switched back to mavenCentral and reverted gradle plugin update in favor of updating it in #256

**Comment by hzsweers** [comment]
build tools 23.0.3... should I just leave it at 23.0.1?

**Comment by JakeWharton** [comment]
You have to update `.travis.yml` if you want to update the build tools

**Comment by hzsweers** [comment]
Now it's giving the same error as #256 :/

**Comment by gabrielittner** [comment]
Travis can't download 23.0.3, .2 is the latest version that works for me. I think the reason might be that the sdk manager isn't completely supported anymore https://code.google.com/p/android/issues/detail?id=185638#c4

**Comment by hzsweers** [comment]
> The standalone SDK manager and command-line sdk manager are no longer receiving updates. For now the single supported tool for SDK management is the SDK manager in Studio.

WTF

**Comment by gabrielittner** [comment]
Sorry, answered before thinking. In this case the issue is probably that you need to update the sdk before it can see the new build-tools version. Add 
```
- tools
- platform-tools
```
to the components block before build-tools.

**Comment by JakeWharton** [comment]
The CLI SDK manager can definitely handle .3 since we use it internally everywhere.

**Comment by hzsweers** [comment]
> Can't create handler inside thread that has not called Looper.prepare()

Is that why there was that internal "swipeRight()" method? It seemed to be flaky on the tests so I switched to the normal espresso one, and the normal one worked fine for me locally :(

**Comment by hzsweers** [comment]
Pulled out the buildtools update to the gradle one. The issues remaining seem like CI issues, and not sure what to do about them

**Pull request closed without merging**
