### PR TITLE
Added RxImageView

### PR DESCRIPTION
**Pull request by Edward608**
Added three actions for ImageView to set its src.
Test cases and resources included.

### CODE REVIEW

**Comment by JakeWharton** [comment]
Can you rebase this on the latest `master`? I just fixed the CI build so if you rebase we should see this pass.

**Comment by Edward608** [comment]
Rebase done

**Comment by Edward608** [comment]
The CI build still fails..

**Comment by JakeWharton** [comment]
It says the Kotlin sources are out-of-date. Did you generate them?

**Comment by Edward608** [comment]
com.jakewharton.rxbinding2.support.v7.widget.RxToolbarTest > navigationClicks[test(AVD) - 4.3.1] FAILED
Test case need to be fixed

**Comment by Edward608** [comment]
Well, the test passes when using emulator with android version 4.3. Can't find cause of failure...

**Comment by OrdonTeam** [comment]
Your latest commit cause error with message `Bindings changed. Did you run 'generateKotlin'?`
Please revert this commit?

**Comment by JakeWharton** [comment]
Thanks for taking the time to do this. Because Java 8 language features are now available in the Android Gradle Plugin 3.0 or newer, you can use `view::setImageResource` (etc.) when subscribing. Per #389 we're not going to add any new simple consumers and deprecate the existing ones.

**Pull request closed without merging**
